### ISSUE TITLE
PHP Warning in Contao 4.4.14

### ISSUE THREAD

**Issue by rorych** [terminal42/header-replay-bundle#15]
Hi there

I just installed Contao 4 on a NGINX Hosting with Reverse Proxy.
After the Installation was finished, i now keep seeing this Warning in the Backend and Frontend.
What could be the issue? Is it the Hosting, should i check with the Hoster?

`Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Terminal42\HeaderReplay\EventListener\HeaderReplayStopPropagationListener' does not have a method 'onKernelResponse' in /home/public_html/contao/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php on line 212
`

Thanks in advance for your Help

**Comment by Toflar** [comment]
Not quite sure what you did, because that listener does not listen to `kernel.response` but `kernel.terminate` instead. Also, there's no need for you to adjust that, this bundle takes care of it on its own (see https://github.com/terminal42/header-replay-bundle/blob/284999da310541bcfea5d6f14d755995a4399cff/src/Resources/config/services.xml#L19-L26). There's nothing you need to configure, maybe you still have leftovers in the cache? Did you try to rebuild it?

**Comment by rorych** [comment]
I didn't change any of the Code/Settings. In my opinion the setup was quite default, but on a new hoster, that i don't know that well. That's why i asked if the hosting has to comply with some kind of conditions? But I'll try to cleanup the cache again and test it after a composer update etc.

**Comment by rorych** [comment]
After composer update and 
`./bin/console cache:clear --no-warmup --env=prod   
./bin/console cache:clear --no-warmup --env=dev`
the problem seems to be solved.

Sorry for bothering.
